version: 3.0.{build}
branches:
  only:
  - portable-3.0

environment:
  version_functional: 0.3.1

image: Visual Studio 2017
platform: Any CPU
shallow_clone: true
init:
- git config --global core.autocrlf true
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- cmd: >-
    dotnet restore
build:
  project: NModbus4.sln
  verbosity: minimal
  
test_script:
- cd NModbus4.UnitTests
- "SET PATH=C:/Users/appveyor/.nuget/packages/OpenCover/4.6.166/tools;C:/Python34;C:/Python34/Scripts;%PATH%"
- OpenCover.Console.exe -oldStyle -register:user -target:"dotnet.exe" -targetargs:"test" -returntargetcode -filter:"+[NModbus4]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:./opencover_report.xml
- pip install codecov
- codecov -f "./opencover_report.xml"

after_build:
- dotnet pack "NModbus4\NModbus4.csproj" -c release --version-suffix %LABEL% -o artifacts
#- ps: Get-ChildItem '**\*.nupkg' | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
- appveyor PushArtifact NModbus4\artifacts\NModbus4.3.0.0-alpha2-%LABEL%.nupkg

artifacts:
- path: NModbus4\artifacts\**\*.*
